/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { MmapReadResult } from 'mellos-mapping-dsh/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d6d6170 {
    read: (sessionId: string) => Promise<RemoteResult<MmapReadResult>>
  }
  interface TypertRemoteMap {
    'mmap/read': (sessionId: string) => Promise<RemoteResult<MmapReadResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mmap': TypertRemoteNamespace$6d6d6170
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
