/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const JsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema))])
const _deepseek_ai_dsh_mmap_host_mmap_read_parameter_0$schema = z.string()
const _deepseek_ai_dsh_mmap_host_mmap_read_result$schema = z.object({
  'cwd': z.union([z.literal(null), z.string()]).readonly(),
  'pages': z.array(z.object({
  'page': z.union([z.literal(null), z.string()]).readonly(),
  'map': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => JsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema))]).readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
  'mtimeMs': z.union([z.literal(null), z.number()]).readonly(),
})).readonly(),
})

export const TYPERT = {
  package: 'mellos-mapping-dsh',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'mellos-mapping-dsh#mmap/read',
      service: 'mmap',
      namespace: 'mmap',
      method: 'read',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'mellos-mapping-dsh#mmap/read:sessionId',
            schema: _deepseek_ai_dsh_mmap_host_mmap_read_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'mellos-mapping-dsh/types#MmapReadResult',
        schema: _deepseek_ai_dsh_mmap_host_mmap_read_result$schema,
      },
      sourceLocation: {"file":"packages/mmap/mmap-host/src/index.ts","line":137,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [
      {
        "description": "Observed change to a watched workspace's Mellos map store: the default page file, the pages directory, or a page file inside it was added, changed, or removed. Coalesced per workspace over the configured debounce window; carries no page detail on purpose — the store is multi-file and a rename touches two paths, so consumers re-read through `mmap.read` instead of patching from event payloads.",
        "summary": "Observed change to a watched workspace's Mellos map store: the default page file, the pages directory, or a page file inside it was added, changed, or removed.",
        "tags": [
          {
            "name": "param",
            "argument": "cwd",
            "comment": "- canonical (realpath) working directory whose store changed.",
            "text": "@param cwd - canonical (realpath) working directory whose store changed.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * Observed change to a watched workspace's Mellos map store: the default\n * page file, the pages directory, or a page file inside it was added,\n * changed, or removed. Coalesced per workspace over the configured\n * debounce window; carries no page detail on purpose — the store is\n * multi-file and a rename touches two paths, so consumers re-read through\n * `mmap.read` instead of patching from event payloads.\n * @param cwd - canonical (realpath) working directory whose store changed.\n * @mode emit\n */",
        "name": "mmap/changed",
        "mode": "emit",
        "signature": "'mmap/changed'(cwd: string): void"
      }
    ],
    "objects": []
  },
}
